=== Axiel30/SEW-LaVuelta2026/xml/etapa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">
	
	<!-- Tipos de datos simples personalizados con restricciones -->
	<xs:simpleType name="tipoLatitud">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="-90.0"/>
			<xs:maxInclusive value="90.0"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="tipoLongitud">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="-180.0"/>
			<xs:maxInclusive value="500.0"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Renombrado a tipoNumeroEtapa -->
	<xs:simpleType name="tipoNumeroEtapa">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="21"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipoOpcionesUnidades">
		<xs:restriction base="xs:string">
			<xs:enumeration value="km"/>
			<xs:enumeration value="km/h"/>
			<xs:enumeration value="m"/>
			<xs:enumeration value="metros"/>
			<xs:enumeration value="grados decimales"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Renombrado a tipoEtapaVuelta -->
	<xs:simpleType name="tipoEtapaVuelta">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Llana"/>
			<xs:enumeration value="Ondulada"/>
			<xs:enumeration value="Media Montaña"/>
			<xs:enumeration value="Montaña"/>
			<xs:enumeration value="Contrarreloj"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Raíz -->
	<xs:element name="trabajo_etapa_vuelta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="numero_etapa" />
				<xs:element ref="nombre_etapa" />
				<xs:element ref="fecha_etapa" />
				<xs:element ref="datos_etapa" />
				<xs:element ref="recorrido" />
				<xs:element ref="hitos_etapa" />
				<xs:element ref="puntos_trayecto_anonimos" />
				<xs:element ref="clasificaciones_carrera" />
				<xs:element ref="referencias_bibliograficas" />
				<xs:element ref="galeria_fotografias" />
				<xs:element ref="galeria_videos" />
				<xs:element ref="galeria_sonidos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Elementos simples y fechas -->
	<!-- Actualizado el type -->
	<xs:element name="numero_etapa" type="tipoNumeroEtapa" />
	<xs:element name="nombre_etapa" type="xs:string" />
	<xs:element name="fecha_etapa" type="xs:date" />
	
	<xs:element name="datos_etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="tiempo_ganador" />
				<xs:element ref="velocidad_media" />
				<xs:element ref="desnivel_acumulado" />
				<xs:element ref="tipo_etapa" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Elementos con valores numéricos y atributos de unidad -->
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoLongitud">
					<xs:attribute name="unidades" type="tipoOpcionesUnidades" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="tiempo_ganador" type="xs:duration" />
	
	<xs:element name="velocidad_media">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="tipoOpcionesUnidades" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="desnivel_acumulado">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidades" type="tipoOpcionesUnidades" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<!-- Actualizado el type -->
	<xs:element name="tipo_etapa" type="tipoEtapaVuelta" />
	
	<xs:element name="recorrido">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lugar_salida" />
				<xs:element ref="lugar_meta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="lugar_salida">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="georreferenciacion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="lugar_meta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="georreferenciacion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="nombre" type="xs:string" />
	
	<xs:element name="georreferenciacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoLatitud">
					<xs:attribute name="unidades" type="tipoOpcionesUnidades" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="tipoOpcionesUnidades" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="hitos_etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="georreferenciacion" />
				<xs:element ref="distancia_salida" />
			</xs:sequence>
			<xs:attribute name="tipo" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="distancia_salida">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="tipoOpcionesUnidades" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="puntos_trayecto_anonimos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="punto_anonimo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="punto_anonimo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="georreferenciacion" />
				<xs:element ref="distancia_salida" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Clasificaciones -->
	<xs:element name="clasificaciones_carrera">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="clasificacion_individual_etapa" />
				<xs:element ref="clasificacion_general" />
				<xs:element ref="clasificacion_equipos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clasificacion_individual_etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="ciclista" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clasificacion_general">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="ciclista" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="ciclista">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="equipo" />
				<xs:choice>
					<xs:element ref="tiempo_etapa" />
					<xs:element ref="tiempo_general" />
				</xs:choice>
				<xs:element minOccurs="0" maxOccurs="1" ref="diferencia" />
			</xs:sequence>
			<xs:attribute name="posicion" type="xs:positiveInteger" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="tiempo_etapa" type="xs:duration" />
	<xs:element name="tiempo_general" type="xs:duration" />
	<xs:element name="diferencia" type="xs:duration" />
	
	<xs:element name="clasificacion_equipos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="equipo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="equipo">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="nombre" />
				<xs:element ref="tiempo_equipos" />
				<xs:element ref="diferencia" />
			</xs:choice>
			<xs:attribute name="posicion" type="xs:positiveInteger" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="tiempo_equipos" type="xs:duration" />
	
	<!-- Referencias -->
	<xs:element name="referencias_bibliograficas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="referencia">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="titulo" />
				<xs:element ref="fuente" />
				<xs:element ref="enlace" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="titulo" type="xs:string" />
	<xs:element name="fuente" type="xs:string" />
	<xs:element name="enlace" type="xs:anyURI" />
	
	<!-- Galerías -->
	<xs:element name="galeria_fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="xs:string" />
	
	<xs:element name="galeria_videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	
	<xs:element name="galeria_sonidos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="sonido" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sonido" type="xs:string" />
	
</xs:schema>

=== Axiel30/SEW-LaVuelta2026/xml/etapaEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<trabajo_etapa_vuelta xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es etapa.xsd">

    <!-- Identificación general de la etapa -->
    <numero_etapa>16</numero_etapa>
    <nombre_etapa>Cortegana-La Rábida.Palos de la Frontera</nombre_etapa>
    <fecha_etapa>2026-09-08</fecha_etapa>

    <!-- Detalles de la etapa -->
    <datos_etapa>
        <longitud unidades="km">181.1</longitud>
        <tiempo_ganador>PT3H56M33S</tiempo_ganador>
        <velocidad_media unidades="km/h">45.935</velocidad_media>
        <desnivel_acumulado unidades="m">2256</desnivel_acumulado>
        <tipo_etapa>Ondulada</tipo_etapa>
    </datos_etapa>

    <!-- Trayecto y Localizaciones Geográficas (Puntos de Salida y Meta) -->
    <recorrido>
        <lugar_salida>
            <nombre>Cortegana</nombre>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.837</longitud>
                <latitud unidades="grados decimales">37.915</latitud>
                <altitud unidades="metros">610.0</altitud>
            </georreferenciacion>
        </lugar_salida>
        <lugar_meta>
            <nombre>La Rábida. Palos de la Frontera</nombre>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.903</longitud>
                <latitud unidades="grados decimales">37.195</latitud>
                <altitud unidades="metros">12.0</altitud>
            </georreferenciacion>
        </lugar_meta>
    </recorrido>

    <!-- Hitos importantes de la etapa (Puertos, Sprints) -->
    <hitos_etapa>
        <hito tipo="Puerto de Fuenteheridos (2ª categoría)">
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.700</longitud>
                <latitud unidades="grados decimales">37.900</latitud>
                <altitud unidades="metros">740.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">22.2</distancia_salida>
        </hito>
        <hito tipo="Alto de Aracena (3ª categoría)">
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.560</longitud>
                <latitud unidades="grados decimales">37.890</latitud>
                <altitud unidades="metros">660.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">33.5</distancia_salida>
        </hito>
        <hito tipo="Alto de Minas de Riotinto (4ª categoría)">
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.590</longitud>
                <latitud unidades="grados decimales">37.690</latitud>
                <altitud unidades="metros">410.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">63.5</distancia_salida>
        </hito>
        <hito tipo="Sprint intermedio bonificado (Villarrasa)">
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.879</longitud>
                <latitud unidades="grados decimales">37.458</latitud>
                <altitud unidades="metros">70.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">114.5</distancia_salida>
        </hito>
    </hitos_etapa>

    <!-- Puntos anónimos para mejorar la precisión del trayecto -->
    <puntos_trayecto_anonimos>
        <!-- Tramo hasta Fuenteheridos -->
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.800</longitud>
                <latitud unidades="grados decimales">37.910</latitud>
                <altitud unidades="metros">530.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">7.0</distancia_salida>
        </punto_anonimo>
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.750</longitud>
                <latitud unidades="grados decimales">37.905</latitud>
                <altitud unidades="metros">680.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">16.0</distancia_salida>
        </punto_anonimo>

        <!-- Tramo Aracena y Minas de Riotinto -->
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.650</longitud>
                <latitud unidades="grados decimales">37.895</latitud>
                <altitud unidades="metros">700.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">28.0</distancia_salida>
        </punto_anonimo>
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.500</longitud>
                <latitud unidades="grados decimales">37.850</latitud>
                <altitud unidades="metros">550.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">40.0</distancia_salida>
        </punto_anonimo>
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.480</longitud>
                <latitud unidades="grados decimales">37.820</latitud>
                <altitud unidades="metros">320.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">47.0</distancia_salida>
        </punto_anonimo>
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.520</longitud>
                <latitud unidades="grados decimales">37.780</latitud>
                <altitud unidades="metros">550.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">53.0</distancia_salida>
        </punto_anonimo>
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.550</longitud>
                <latitud unidades="grados decimales">37.750</latitud>
                <altitud unidades="metros">380.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">58.0</distancia_salida>
        </punto_anonimo>

        <!-- Caídas abruptas hacia La Palma del Condado -->
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.600</longitud>
                <latitud unidades="grados decimales">37.650</latitud>
                <altitud unidades="metros">300.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">68.0</distancia_salida>
        </punto_anonimo>
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.610</longitud>
                <latitud unidades="grados decimales">37.600</latitud>
                <altitud unidades="metros">200.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">74.0</distancia_salida>
        </punto_anonimo>
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.620</longitud>
                <latitud unidades="grados decimales">37.550</latitud>
                <altitud unidades="metros">350.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">78.0</distancia_salida>
        </punto_anonimo>
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.600</longitud>
                <latitud unidades="grados decimales">37.500</latitud>
                <altitud unidades="metros">120.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">85.0</distancia_salida>
        </punto_anonimo>
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.580</longitud>
                <latitud unidades="grados decimales">37.450</latitud>
                <altitud unidades="metros">320.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">92.0</distancia_salida>
        </punto_anonimo>
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.560</longitud>
                <latitud unidades="grados decimales">37.420</latitud>
                <altitud unidades="metros">110.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">100.0</distancia_salida>
        </punto_anonimo>
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.555</longitud>
                <latitud unidades="grados decimales">37.400</latitud>
                <altitud unidades="metros">80.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">105.0</distancia_salida>
        </punto_anonimo>

        <!-- Tramos llanos y repechos finales hacia la meta -->
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.850</longitud>
                <latitud unidades="grados decimales">37.400</latitud>
                <altitud unidades="metros">50.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">120.0</distancia_salida>
        </punto_anonimo>
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.800</longitud>
                <latitud unidades="grados decimales">37.350</latitud>
                <altitud unidades="metros">15.0</altitud>
            </georreferenciacion>
            <distancia_salida unidades="km">128.0</distancia_salida>
        </punto_anonimo>
        <punto_anonimo>
            <georreferenciacion>
                <longitud unidades="grados decimales">-6.780</longitud>
